### ISSUE TITLE
'\' escaped characters break preceding string appends

### ISSUE THREAD

**Issue by mnuster** [Mellow-Programming-Language/Mellow#26]
The writeln() with escaped quotations:

```
extern func writeln(str: string);

func main() {
    writeln("Missing:" ~ " \'string\'" ~ " appended" ~ " text");
}
```

produces the output:

```
Missing: 'string'
```

**Comment by CollinReeser** [comment]
After extensive testing to figure this one out, it turns out the appends actually _do_ work, it is simply that the backslash character itself is erroneously included in the new string's length, but doesn't actually exist in the string, so the null-terminator at the end of the original string fails to be overwritten by the over-by-one newly-appended string.
