### ISSUE TITLE
Implement shorthand for variable modifications, including increment and decrement syntax

### ISSUE THREAD

**Issue by iSlinger** [Mellow-Programming-Language/Mellow#45]
Ticket name isn't great (feel free to change it and remove this line).

Variable mutation syntax should have similar shorthand to what is familiar to most from other languages such as C/C++/etc.

An example: Current implementation for variable increment is the following:

```
i = i + 1;
```

The implementation of the shorter methods of variable mutation is useful, and after these changes the three statements should be equivalent.

```
i = i + 1;
i++;
i += 1;
```

This ticket should also act as a reminder to have all operations have this enhancement.

```
i += 1;
i -= 1;
i *= 1;
i /= 1;
//if supported
i |= 1;
i ~= 1;
i &= 1;
```

**Comment by CollinReeser** [comment]
All op-equals forms will be implemented, but pre- and post-increment/decrement will not be implemented. This is because the order in which multiple increments and/or decrements of one or more variables in a complex expression is not necessarily clearly obvious, and generally makes for non-obvious code.

**Comment by CollinReeser** [comment]
Implemented for integer types. Floating-point equivalents will be implemented when float-support is introduced.
